spring:
  application:
    name : my-restful-service
  messages:
    basename: messages

  security:
    user:
      name: seoin
      password: 123qwe
      roles: ADMIN


server:
  port: 8088

logging:
  level:
    org.springframework: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"


